services:
  settlemint-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: settlemint-service
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    restart: unless-stopped
