services:
  settlemint-mongo:
    image: mongo:8.0
    container_name: settlemint-mongo
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  settlemint-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: settlemint-service
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    depends_on:
      settlemint-mongo:
        condition: service_healthy
    restart: unless-stopped

volumes:
  mongo-data:
